project:
  type: website
  output-dir: docs
website:
  title: "presentation-ordinal-regression"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ordinal_regression.qmd
        text: Presentation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



